### ISSUE TITLE
Tests not showing up in report

### ISSUE THREAD

**Issue by jacobsorme** [dd2480group7/piqueserver#4]
When running as in #1, on the branch `issue/3` with new tests, the files that the tests are supposed to test does _not_ show up in coverage report. The tests are being ran. Why is this?

**Comment by admredbeard** [comment]
Found what caused the issue #4. In .coveragerc file omit causes files in those folders to be excluded in report. Thanx to me.
![fail](https://user-images.githubusercontent.com/26894696/52787967-c8c6aa00-305f-11e9-99b6-f1a276728aa7.png)
